### ISSUE TITLE
[FEAT] <How to connect Zetoro on docker to extention of our browser?>

### ISSUE THREAD

**Issue by Shahin-rmz** [linuxserver/docker-zotero#5]
### Is this a new feature request?

- [x] I have searched the existing issues

### Wanted change

Hi, thanks so much for dockerizing Zetoro. it can help human science a lot.
I want to know how can we connect Zetoro which is running to localhost to extention of our local browser?

### Reason for change

It saves so much time if we connect our browser to Zetoro

**Comment by j0nnymoe** [comment]
You would need to check their documentation if the extension can connect to remote instances. If it can do that, then it's possible.

**Comment by Shahin-rmz** [comment]
Thanks for reply @j0nnymoe 
already done that, 

![Image](https://github.com/user-attachments/assets/09cea422-776c-47b0-8100-69ffe94df180)
in the preference it could theoretically connect to any url.
however, it could not connect to `http://host.docker.internal:3001` or other ports.

**Comment by j0nnymoe** [comment]
You will need to expose the additional port to how you've deployed the container and that should allow the extension to connect.

**Comment by Shahin-rmz** [comment]
```
---
services:
  zotero:
    image: lscr.io/linuxserver/zotero:latest
    container_name: zotero
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3001:3001
      - 23119:23119
    shm_size: "1gb"
    restart: unless-stopped
```
this is my docker compose yaml and this is the extention setting

![Image](https://github.com/user-attachments/assets/1365d962-5c32-4f4e-ba3c-3f3bbdcba91e)
still got problem. 
changed debug level from 5 to 1 to see the error can paste it here but still gave me vague general error.
